name: ${project.name}
main: net.daboross.bukkitdev.skywars.SkyWarsPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
url: ${project.url}
softdepend: [Vault]
commands:
  skywars:
    aliases: [sw]
  skywarssetup:
    aliases: [sws]
